### ISSUE TITLE
Pydeface 1.1.0 now broken

### ISSUE THREAD

**Issue by tkkuehn** [khanlab/tar2bids#36]
Running tar2bids with `-D`, I encountered this error:

```
pydeface --verbose --force /datasets/tmpx67c77nw/incoming/sub-0018/anat/sub-0018_acq-MP2RAGEpostproc_run-01_T1w.nii.gz --applyto /datasets/tmpx67c77nw/incoming/sub-0018/anat/sub-0018_acq-MP2RAGE_run-01_T1map.nii.gz /datasets/tmpx67c77nw/incoming/sub-0018/anat/sub-0018_acq-UNI_run-01_MP2RAGE.nii.gz /datasets/tmpx67c77nw/incoming/sub-0018/anat/sub-0018_inv-1_run-01_MP2RAGE.nii.gz /datasets/tmpx67c77nw/incoming/sub-0018/anat/sub-0018_inv-2_run-01_MP2RAGE.nii.gz
Traceback (most recent call last):
  File "/usr/local/bin/pydeface", line 33, in <module>
------------
pydeface 2.0
------------
Temporary files:
  /tmp/tmp5b6jac6a/tmp4ac2fcgn.mat
  /tmp/tmp5b6jac6a/tmpvx126jaz.nii.gz
Defacing...
  /datasets/tmpx67c77nw/incoming/sub-0018/anat/sub-0018_acq-MP2RAGEpostproc_run-01_T1w.nii.gz
    sys.exit(load_entry_point('pydeface==2.0', 'console_scripts', 'pydeface')())
  File "/usr/local/lib/python3.9/dist-packages/pydeface-2.0-py3.9.egg/pydeface/__main__.py", line 120, in main
  File "/usr/local/lib/python3.9/dist-packages/nibabel/deprecator.py", line 181, in deprecated_func
    raise error_class(message)
nibabel.deprecator.ExpiredDeprecationError: get_affine method is deprecated.
Please use the ``img.affine`` property instead.

* deprecated from version: 2.1
* Raises <class 'nibabel.deprecator.ExpiredDeprecationError'> as of version: 4.0
```

See https://github.com/poldracklab/pydeface/issues/46, which is solved in the more recent versions of pydeface. I can't see any reason not to just update the version we use, but @akhanf can you confirm?

**Comment by akhanf** [comment]
Yep I don't see any issue with just updating the version!
